In [7]:
import torch

In [8]:
torch.empty(5,3)

tensor([[ 0.0000e+00,  0.0000e+00,  2.4627e-25],
        [-3.6232e-41,  2.7909e+23,  0.0000e+00],
        [ 5.6052e-44,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  2.1019e-44,  0.0000e+00],
        [-9.7869e-19,  1.0019e-42, -1.0230e-18]])

In [9]:
torch.rand(5,3)

tensor([[0.0173, 0.8706, 0.9769],
        [0.1456, 0.0665, 0.4219],
        [0.3738, 0.7916, 0.9286],
        [0.9488, 0.4252, 0.8110],
        [0.0102, 0.0545, 0.3870]])

In [10]:
torch.zeros(5,3, dtype = torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [15]:
a = [[1,2],
     [3,4]]

x=torch.tensor(a)

In [16]:
x.new_ones(5,3, dtype = torch.double)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)